### ISSUE TITLE
你好，请问拖拽是用什么插件实现的

### ISSUE THREAD

**Issue by fengcanluoye** [xiaoai7904/web_designer#19]
你好，请问拖拽是用什么插件实现的

**Comment by xiaoai7904** [comment]
1.画布区的组件缩放用的是[vue-draggable-resizable](https://github.com/mauricius/vue-draggable-resizable)
2.拖拽组件到画布区用的是js原生事件(Drag)

**Comment by fengcanluoye** [comment]
额，代码看的一脸懵逼，这是vue写的？

**Comment by xiaoai7904** [comment]
> 额，代码看的一脸懵逼，这是vue写的？

嗯 用vue写的

**Comment by changguichun88** [comment]
您好，可以问下咱们这个可一次多选几个图形么？
