### ISSUE TITLE
本地部署，发布成功后，按照命令进行安装npm install，然后进行运行npm run serve就报如下错误，大神可有高招？

### ISSUE THREAD

**Issue by MrForJewel** [xiaoai7904/web_designer#36]
This relative module was not found:

* ../pluginsMixins in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/plugins/calendar/calendar.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/plugins/table/table.vue?vue&type=script&lang=js&

**Comment by xiaoai7904** [comment]
之前添加了设计器事件配置功能,运行态未支持导致文件缺失
你可以重新拉最新代码在试一试，目前运行态已经支持事件配置功能
