### ISSUE TITLE
大佬

### ISSUE THREAD

**Issue by zhouwei007** [xiaoai7904/web_designer#41]
大佬自适应布局和容器组件 拖拽完后 宽度 还是平铺整个屏幕。没办法布局

**Comment by xiaoai7904** [comment]
自适应布局使用的三方库，默认我设置的是沾满整个屏幕，整个容器组件个自适应组件后期需要更新，目前只是一个初版
目前在考虑新增自由布局，布局方法完全交给用户自己决定，比如:某个组件定位，浮动，flex等

很欢迎你提出好的想法
