### ISSUE TITLE
布局问题

### ISSUE THREAD

**Issue by zhouwei007** [xiaoai7904/web_designer#42]
1，自由布局 其他组件无法拖拽到容器组件里
2，定位布局 使用容器组件后 把组件拖入到容器组件后 不管怎么拖拽改变宽度 预览和生成模板都会宽度失效会独占一行
3，设置宽度 和 高度目前只能用px 能变换单位就好了
4，楼主如果觉得方便的话 我可以参与一起开发更新这个布局器

**Comment by xiaoai7904** [comment]
容器组件只是一个初版，没有进一步去优化
最近一段时间都很忙，所以就一直没有去更新，很欢迎你参与该项目开发，有什么好的想法可以大胆的提出

**Comment by zhouwei007** [comment]
好的 我会按着我使用遇到问题 然后列出需求。我们一同解决

**Comment by xiaoai7904** [comment]
目前主要需要解决的就是 自适应布局问题和代码生成结构问题

自适应问题，目前的想法是通过参照 Bootstrap 的 响应式设计来完成，必须依赖容器组件

所以目前这个容器组件是满足不了需求的，需要进行重构

**Comment by zhouwei007** [comment]
很多组件需要通过solt 插入其他组件或者标签 目前不支持。能加vw吗 我的 17319262607
